"""Enhanced models for exam analytics & future features

Revision ID: dba304391410
Revises: f2816d536ad6
Create Date: 2025-07-25 11:21:29.450769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dba304391410'
down_revision = 'f2816d536ad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option', sa.String(length=1), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('time_spent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['test_attempt.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignment_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('improvement_score', sa.Float(), nullable=True))

    with op.batch_alter_table('student_analytics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('history', sa.JSON(), nullable=True))

    with op.batch_alter_table('student_class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('joined_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_minutes', sa.Integer(), nullable=True))

    with op.batch_alter_table('test_attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_taken', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_attempt', schema=None) as batch_op:
        batch_op.drop_column('time_taken')

    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.drop_column('duration_minutes')

    with op.batch_alter_table('student_class', schema=None) as batch_op:
        batch_op.drop_column('joined_at')

    with op.batch_alter_table('student_analytics', schema=None) as batch_op:
        batch_op.drop_column('history')

    with op.batch_alter_table('assignment_submission', schema=None) as batch_op:
        batch_op.drop_column('improvement_score')

    op.drop_table('student_answer')
    # ### end Alembic commands ###
