"""Future-ready schema with topics, analytics & assignments

Revision ID: f2816d536ad6
Revises: 419075dfd3bd
Create Date: 2025-07-24 19:08:53.350091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2816d536ad6'
down_revision = '419075dfd3bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.String(length=20), nullable=True))

    with op.batch_alter_table('test_attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_questions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('correct_answers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wrong_answers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('topic_performance', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_attempt', schema=None) as batch_op:
        batch_op.drop_column('topic_performance')
        batch_op.drop_column('wrong_answers')
        batch_op.drop_column('correct_answers')
        batch_op.drop_column('total_questions')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('difficulty')
        batch_op.drop_column('topic')

    # ### end Alembic commands ###
